version:  '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_HOST
      - MYSQL_PASSWORD
      -
    volumes:
      - ./db/data:/var/lib/mysql



  redis:
    image: redis:7.0
    container_name: redis


