version:  '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=
      - DB_SCHEMA=
      - DB_USER=
      - DB_PASSWORD=
      - SPRING_REDIS_HOST=
      - SPRING_REDIS_PORT=
      - JWT_ACCESS_SECRET=
      - JWT_REFRESH_SECRET=
      - JWT_ACCESS_TIME=
      - JWT_REFRESH_TIME=
      - GAUTH_CLIENTID=
      - GAUTH_CLIENT_SECRET=
      - GAUTH_REDIRECT_URI=
    ports:
      - 80:8080
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:



  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - 6379:6379


