version: '3'
services:
  app:
    image: seolhee/gmt-backend-v2_app:latest
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./.env
    ports:
      - 80:8080
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - backend


  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend
    environment:
      REDIS_HOST: ${{ env.SPRING_REDIS_HOST }}
      REDIS_PORT: 6379

networks:
  backend: