name: gmt-back-workflow

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["*"]

env:
  DOCKER_HUB_USERNAME: seolhee
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
  DB_USER: ${{ secrets.DB_USER }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_PROJECT_IMAGE_NAME: ${{ secrets.DOCKER_PROJECT_IMAGE_NAME }}
  EC2_ADDRESS: ${{ secrets.EC2_ADDRESS }}
  ENV: ${{ secrets.ENV }}
  GAUTH_CLIENTID: ${{ secrets.GAUTH_CLIENTID }}
  GAUTH_CLIENT_SECRET: ${{ secrets.GAUTH_CLIENT_SECRET }}
  GAUTH_REDIRECT_URI: ${{ secrets.GAUTH_REDIRECT_URI }}
  JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
  JWT_ACCESS_TIME: ${{ secrets.JWT_ACCESS_TIME }}
  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
  JWT_REFRESH_TIME: ${{ secrets.JWT_REFRESH_TIME }}
  SPRING_REDIS_HOST: ${{ secrets.SPRING_REDIS_HOST }}
  SPRING_REDIS_PORT: ${{ secrets.SPRING_REDIS_PORT }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  gmt-back-workflow:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_SCHEMA: ${{ env.DB_SCHEMA }}
          DB_USER: ${{ env.DB_USER }}
        ports:
         - 3306:3306

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Gradle Init
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Print Current Directory
        run: |
          echo "Current Directory:"
          pwd

      - name: List Files
        run: |
          echo "Files in the current directory:"
          ls

      - name: Setup execute Gradle's permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Docker-Hub Login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: seolhee
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Docker Image Build & Push
        run: |
          docker build --tag seolhee/${{ env.DOCKER_PROJECT_IMAGE_NAME }}:latest
          docker push seolhee/${{ env.DOCKER_PROJECT_IMAGE_NAME }}:latest


        








