name: GMT-BACK-CI

on:
  push:
    branches: ["develop"]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Init Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Set up JDK 11 (job success)
        if: ${{ success() }}
        run: echo "Set up JDK 11 is succeeded"

      - name: Setup Gradle's permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        
      - name: backend-ci-success
        if: ${{ success() }}
        uses: discord/send-message@v2
        with: 
          title: gmt-back-ci-success 🚀🚀
          webhook_url: ${{ secrets.WEBHOOK22 }}

      - name: backend-ci-failed
        if: ${{ failure() }}
        uses: discord/send-message@v2
        with: 
          title: gmt-back-ci-falied 😖😱
          webhook_url: ${{ secrets.WEBHOOK22 }} 

